# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
